defaults: &defaults
  working_directory: ~/typesettable
  docker:
    - image: circleci/node:8.8.1-browsers-legacy

restore_yarn_cache: &restore_yarn_cache
  restore_cache:
    name: Restore Yarn Package Cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}

yarn_install: &yarn_install
  run:
    name: Install Dependencies
    command: yarn install --pure-lockfile

save_yarn_cache: &save_yarn_cache
  save_cache:
    name: Save Yarn Package Cache
    key: yarn-packages-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn


version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_yarn_cache
      - *yarn_install
      - *save_yarn_cache
      - run: yarn test
  # deploy:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run:
  #         name: preview
  #         branch:
  #           only: master
  #         command: |-
  #           npm run preview
  #           ./preview/demo.js
  #     - run:
  #         name: npm
  #         owner: palantir
  #         command: |-
  #           npm run build
  #           git diff HEAD..origin/master --quiet || (echo "dist not built"; exit 1)
  #           npm run -s check_version || (echo "package.json version not updated"; exit 1)
  #           echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
  #           npm publish

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - deploy
