version: 2

jobs:
  build:
    environment:
      PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"
    docker: # run the steps with Docker
      - image: circleci/node:8.8.1 
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn      
  test:
    steps:
      - checkout
      - run: yarn test
      
  deployment:
    steps:
      - checkout
      - run:
        name: preview
        branch: /.*/
        command: |-
          npm run preview
          ./preview/demo.js
      - run:
        name: npm
        owner: palantir
        command: |-
          npm run build
          git diff HEAD..origin/master --quiet || (echo "dist not built"; exit 1)
          npm run -s check_version || (echo "package.json version not updated"; exit 1)
          echo -e "$NPM_USER\n$NPM_PASS\n$NPM_EMAIL" | npm login
          npm publish